### ISSUE TITLE
Missing Blend Layers Option

### ISSUE THREAD

**Issue by OTMackan** [Mignari/ObjectBuilder#41]
I have noticed that some items have more than 1 extra layer (example 18009 and more in that area). These items can't be edited in all layers, which proves to be a bit of a problem since the third layer is bugged.

I've been trying to work out a fix for it myself (with virtually no knowledge what so ever in actionscript).
I did manage to get it to show the layer, but if I slide it for next animation I get a lot of errors. Maybe someone more experienced with actionscript could take a look at it?

I practically copied the "blendLayer" stuff and made a new one called "blendNextLayer"
(I only edited ThingTypeEditor.mxml and ThingDataView.as + locales)

I only worked for an edit to show blend layer 3. Maybe something should be fixed with a slider or something to show all blend layers if there are more than those?

Ps. This software is really great and I hope you would keep working on it!

**Comment by Mignari** [comment]
Hi, @OTMackan 
Thanks for the report. I will create a branch to show how to fix it, until I get back to development.

**Comment by OTMackan** [comment]
Thank you! :)
